# =====================================
# Docker profile - prepared for future use
# =====================================
spring.data.mongodb.uri=mongodb://mongoadmin:password@mongodb:27017/my-db?authSource=admin
spring.data.mongodb.database=my-db

server.port=8080