# =======================================
# Base Spring config
# Local: ./mvnw spring-boot:run
# =======================================
spring.data.mongodb.uri=mongodb://mongoadmin:password@localhost:27017/my-db?authSource=admin
spring.data.mongodb.database=my-db

server.port=8080